server:
  port: 8080
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.110.128:3306/all
    username: root
    password: yxt123
    druid:
      driver-class-name: ${spring.datasource.driver-class-name}
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      max-active: 20
      filter:
        stat:
          enabled: true
          db-type: mysql
          slow-sql-millis: 1000
          log-slow-sql: true

logging:
  config: classpath:logback-spring.xml
  level:
    web: debug



