server:
  port: 8081
  servlet:
    context-path: /msg

spring:
  application:
    name: msg-service
  web:
    resources:
      static-locations: classpath:/static/**

logging:
  config: classpath:logback-spring.xml
  level:
    web: debug



